-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * SUM(O.SALES_AMOUNT) SALES
  FROM PRODUCT       P 
     , OFFLINE_SALE  O
WHERE 1=1
  AND P.PRODUCT_ID(+) = O.PRODUCT_ID
GROUP BY PRODUCT_CODE, P.PRICE
ORDER BY SALES DESC, P.PRODUCT_CODE