-- 코드를 작성해주세요
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS 'PARENT_GENOTYPE'
FROM ECOLI_DATA A
JOIN ECOLI_DATA B
ON A.PARENT_ID = B.ID
WHERE (A.GENOTYPE & B.GENOTYPE >= B.GENOTYPE)
ORDER BY A.ID
;
#부모는 ID 3 이며 부모의 형질 1, 2번 중 2 번 형질을 보유하고 있지 않습니다.