-- 코드를 입력하세요
SELECT B.BOOK_ID, TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM BOOK B
WHERE 1=1
  AND TO_CHAR(B.PUBLISHED_DATE, 'YYYY') = '2021'
  AND B.CATEGORY = '인문'
ORDER BY PUBLISHED_DATE 
;