-- 코드를 작성해주세요
SELECT SUM(SCORE) AS 'SCORE', H.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE H
JOIN HR_EMPLOYEES E ON H.EMP_NO = E.EMP_NO
JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY H.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
;