-- 코드를 입력하세요
SELECT '/home/grep/src/' || F.BOARD_ID || '/' 
        || F.FILE_ID || F.FILE_NAME || F.FILE_EXT FILE_PATH
  FROM USED_GOODS_BOARD B
     , USED_GOODS_FILE  F
WHERE 1=1
  AND B.BOARD_ID = F.BOARD_ID(+)
  AND B.VIEWS = (SELECT MAX(B2.VIEWS)
                  FROM USED_GOODS_BOARD B2)
ORDER BY F.FILE_ID DESC